### PR TITLE
Update For better RTL View

### PR DESCRIPTION
**Pull request by mortezasun**
remove
   android:layout_alignLeft="@android:id/title"
            android:layout_alignStart="@android:id/title"

### CODE REVIEW

**Comment by michael-rapp** [comment]
I tested this and it seems to make no difference when using the RTL layout. In Android's official `preference.xml` file the `android:layout_alignStart` attribute is included as well (see e.g. http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.1.1_r1/frameworks/base/core/res/res/layout/preference.xml/).

To me the preferences look well when using the RTL layout. Do you encounter any issues? If yes, a screenshot and more information about your device and Android version would be helpful.

**Comment by mortezasun** [comment]
in default mode : android 4.2.2 , Api 17 , 320 dpi, 1280*768 , genymotion
image 1

after remove 
android:layout_alignLeft="@android:id/title"
android:layout_alignStart="@android:id/title"
 
image 2


Also in xlarge screen rtl view don't work correctly because assign  margins in code
Google Nexus 9  android 6  Api 23 
image 4

after change left margin to right margin : 
image 3

**Comment by michael-rapp** [comment]
Your changes are now part of version 4.2.11 of the library. I also fixed the hardcoded margins on tablets together with other minor RTL improvements. Thank you for your contribution.

**Comment by mortezasun** [comment]
thank you for your awesome library

**Comment by mortezasun** [comment]
I'm sorry, little bug in Orientation change , not keep state, 
first launch: in android 6 api 23 

image 6

and then rotate
image 5

**Comment by michael-rapp** [comment]
I will investigate on this, but it will take a few days.

**Pull request merged**
